engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
ratings:
  paths:
  - "src/Event/**"
exclude_paths:
- "src/Test/*"
